const XLSX = require('xlsx');

function makeSheet(rows) {
  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!cols'] = [{ wch: 5 }, { wch: 68 }, { wch: 55 }];
  return ws;
}

const sections = [

  // ── SHEET 0 : INSTRUCTIONS ─────────────────────────────────────────────────
  {
    name: 'READ ME FIRST',
    rows: [
      ['SCOPE AI HUB — Website Content Questionnaire'],
      [''],
      ['HOW TO USE THIS FILE:'],
      ['1. Go through each sheet (tab) one by one.'],
      ['2. Fill in the "Your Answer" column in yellow.'],
      ['3. For media files (photos, videos), share a Google Drive folder link.'],
      ['4. Return the completed file to your developer.'],
      [''],
      ['SHEETS IN THIS FILE:', '', ''],
      ['Sheet', 'Page / Section', 'Priority'],
      ['1. Branding & Contact', 'All pages (used everywhere)', 'CRITICAL'],
      ['2. Social Media', 'Footer, Contact page', 'High'],
      ['3. Home Page', 'Homepage only', 'CRITICAL'],
      ['4. About Page', 'About Us page', 'CRITICAL'],
      ['5. Courses Offered', 'Courses list & course detail', 'CRITICAL'],
      ['6. Trainers & Team', 'About page & Trainer Profiles page', 'CRITICAL'],
      ['7. Admissions & Fees', 'Admissions page', 'High'],
      ['8. Student Testimonials', 'Home page & Reviews page', 'High'],
      ['9. FAQ Page', 'FAQ page — 18 real answers needed', 'Medium'],
      ['10. Join As Trainer', 'Careers — Join as Trainer page', 'Medium'],
      ['11. Legal & Policies', 'Privacy Policy, Refund Policy, T&C', 'High'],
      ['12. Media Assets', 'All pages with photos/videos', 'CRITICAL'],
      ['13. Live Chat (Optional)', 'Site-wide chat widget', 'Optional'],
    ],
  },

  // ── SHEET 1 : BRANDING & CONTACT ─────────────────────────────────────────
  {
    name: '1. Branding & Contact',
    rows: [
      ['#', 'Question', 'Your Answer'],
      ['', '--- INSTITUTE IDENTITY ---', ''],
      [1,  'Full institute name (as it should appear on the website)', 'SCOPE AI HUB'],
      [2,  'Tagline / slogan (one line shown under the name)', 'AI SKILLS FOR NEXT GEN'],
      [3,  'Founded / Established year', ''],
      [4,  'Short 2-3 line description of the institute (for website SEO)', ''],
      ['', '--- CONTACT DETAILS ---', ''],
      [5,  'Full physical address (building, street, area, city, pincode)', ''],
      [6,  'Primary phone number (with country code)', ''],
      [7,  'Primary email address (for inquiries)', ''],
      [8,  'WhatsApp number — same as phone or different?', ''],
      ['', '--- OFFICE HOURS (for Contact page) ---', ''],
      [9,  'Monday to Friday — opening time and closing time', ''],
      [10, 'Saturday — opening time and closing time', ''],
      [11, 'Sunday — Open or Closed?', ''],
      ['', '--- MAPS ---', ''],
      [12, 'Google Maps embed link to your exact campus location', ''],
    ],
  },

  // ── SHEET 2 : SOCIAL MEDIA ────────────────────────────────────────────────
  {
    name: '2. Social Media',
    rows: [
      ['#', 'Platform', 'Your Profile URL'],
      [13, 'Facebook Page URL', ''],
      [14, 'Instagram Profile URL', ''],
      [15, 'LinkedIn Company Page URL', ''],
      [16, 'Twitter / X Profile URL', ''],
      [17, 'YouTube Channel URL (if any)', ''],
    ],
  },

  // ── SHEET 3 : HOME PAGE ───────────────────────────────────────────────────
  {
    name: '3. Home Page',
    rows: [
      ['#', 'Section — Question', 'Your Answer'],
      ['', '--- HERO SECTION (top banner) ---', ''],
      [18, 'Hero badge text (small label above the title, e.g. "No.1 Rated Institute" — confirm or change)', 'No.1 Rated Institute'],
      [19, 'Hero main title — Line 1 (e.g. "Master Tech Skills.")', ''],
      [20, 'Hero main title — Line 2 (e.g. "Launch Your Career.")', ''],
      [21, 'Hero subtitle / description (1–2 line tagline under the title)', ''],
      ['', '--- KEY STATS (shown below hero) ---', ''],
      [22, 'Stat 1 label & number — e.g. "Practical Projects — 50+"', ''],
      [23, 'Stat 2 label & number — e.g. "Instructor Experience — 15+ Years"', ''],
      [24, 'Stat 3 label & number — e.g. "Curriculum Rating — 4.9/5"', ''],
      [25, 'Stat 4 label & number — e.g. "Hiring Partners — 100+"', ''],
      ['', '--- CERTIFICATIONS & RECOGNITIONS (logos shown on home page) ---', ''],
      [26, 'Is NASSCOM certification real? (Yes/No)', ''],
      [27, 'Is ISO certification real? (Yes/No) — if Yes, which standard?', ''],
      [28, 'Is MSME registration real? (Yes/No)', ''],
      [29, 'Is FutureSkills Prime affiliation real? (Yes/No)', ''],
      ['', '--- TRUST FACTORS (3 highlighted points) ---', ''],
      [30, 'Trust Factor 1 title & description (currently: NASSCOM Certification)', ''],
      [31, 'Trust Factor 2 title & description (currently: Bilingual Instruction)', ''],
      [32, 'Trust Factor 3 title & description (currently: Expert-Led Mentorship)', ''],
      ['', '--- LEARNING METHODOLOGY (4 steps shown on home page) ---', ''],
      [33, 'Step 1 title & short description (currently: Dedicated Lab Support)', ''],
      [34, 'Step 2 title & short description (currently: Real-time Training)', ''],
      [35, 'Step 3 title & short description (currently: 1:1 Expert Mentorship)', ''],
      [36, 'Step 4 title & short description (currently: Placement Guidance to Get Hired)', ''],
      ['', '--- HIRING PARTNERS MARQUEE (company logos shown scrolling) ---', ''],
      [37, 'Are any of these real companies that hired your students? (Yes/No for each)', ''],
      [38, 'Google', ''],
      [39, 'Amazon', ''],
      [40, 'Microsoft', ''],
      [41, 'Zoho', ''],
      [42, 'Freshworks', ''],
      [43, 'TCS', ''],
      [44, 'Infosys', ''],
      [45, 'Wipro', ''],
      [46, 'Any other companies to add?', ''],
      ['', '--- HOME PAGE TESTIMONIALS (3 shown on home page) ---', ''],
      [47, 'Student 1 — Name, Role & Company, Testimonial text, Photo', ''],
      [48, 'Student 2 — Name, Role & Company, Testimonial text, Photo', ''],
      [49, 'Student 3 — Name, Role & Company, Testimonial text, Photo', ''],
      ['', '--- PLACEMENT STATS (shown in placement section) ---', ''],
      [50, 'Average starting salary for freshers (currently: 4-8 LPA)', ''],
      [51, 'Percentage of students placed within 6 months (currently: 90%)', ''],
      [52, 'Number of active hiring partners (currently: 50+)', ''],
      ['', '--- CORPORATE TRAINING SECTION ---', ''],
      [53, 'Do you offer corporate / bulk training to companies? (Yes/No)', ''],
      [54, 'If Yes — number of corporates trained so far (currently: 50+)', ''],
      [55, 'If Yes — number of employees upskilled so far (currently: 10k+)', ''],
    ],
  },

  // ── SHEET 4 : ABOUT PAGE ──────────────────────────────────────────────────
  {
    name: '4. About Page',
    rows: [
      ['#', 'Section — Question', 'Your Answer'],
      ['', '--- FOUNDING STORY (Hero subtitle on About page) ---', ''],
      [56, 'In 1-3 sentences: What is the founding story of Scope AI Hub? Why was it started?', ''],
      [57, 'Year it was established', ''],
      [58, 'Who founded it? (Name, background of founder)', ''],
      ['', '--- OUR GOAL & WHAT DRIVES US ---', ''],
      [59, '"Our Goal" — 2-3 sentences about the institute\'s main purpose', ''],
      [60, '"What Drives Us" — 2-3 sentences about motivation / vision', ''],
      ['', '--- ABOUT PAGE STATS (4 numbers shown) ---', ''],
      [61, 'Stat 1 — Industry Projects (currently: 50+)', ''],
      [62, 'Stat 2 — Instructor Experience (currently: 15+ years)', ''],
      [63, 'Stat 3 — Hiring Partners (currently: 50+)', ''],
      [64, 'Stat 4 — Practical Focus (currently: 100%)', ''],
      ['', '--- CORE VALUES (4 values shown) ---', ''],
      [65, 'Value 1 title & description (currently: Official Certification)', ''],
      [66, 'Value 2 title & description (currently: Guidance for Placement)', ''],
      [67, 'Value 3 title & description (currently: Outcome-Driven)', ''],
      [68, 'Value 4 title & description (currently: Bilingual Instruction)', ''],
      ['', '--- OUR PRESENCE (campus / online locations) ---', ''],
      [69, 'Campus name (currently: Chennai Campus)', ''],
      [70, 'Campus full address', ''],
      [71, 'Campus phone number', ''],
      [72, 'Campus Google Maps link', ''],
      [73, 'Do you serve online students internationally? Which countries/regions?', ''],
      ['', '--- TEAM (3 team members shown on About page) ---', ''],
      [74, 'Team member 1 — Name, Designation, Bio (2-3 lines), Expertise tags, Photo', ''],
      [75, 'Team member 2 — Name, Designation, Bio (2-3 lines), Expertise tags, Photo', ''],
      [76, 'Team member 3 — Name, Designation, Bio (2-3 lines), Expertise tags, Photo', ''],
    ],
  },

  // ── SHEET 5 : COURSES ─────────────────────────────────────────────────────
  {
    name: '5. Courses Offered',
    rows: [
      ['#', 'Question (Fill for EACH course you offer — add rows as needed)', 'Your Answer'],
      ['', '--- FIRST, LIST ALL YOUR COURSES ---', ''],
      [77, 'List all courses you currently offer (one per line)', ''],
      ['', '--- FOR EACH COURSE, FILL THE FOLLOWING ---', ''],
      [78, 'Course title (exact name)', ''],
      [79, 'Course category (e.g. Development / Design / Data Science)', ''],
      [80, 'Duration (e.g. 24 weeks)', ''],
      [81, 'Level (Beginner / Intermediate / Advanced / Beginner to Advanced)', ''],
      [82, 'Fee / Price (in Rs.) — exact amount', ''],
      [83, 'Mode — Online / Offline / Hybrid', ''],
      [84, 'Next batch start date', ''],
      [85, 'Short description (2-3 lines about what the course covers)', ''],
      [86, 'Who is this course for? (target audience)', ''],
      [87, 'What will students learn? (5-6 key outcomes)', ''],
      [88, 'Prerequisites (what prior knowledge is needed, if any)', ''],
      [89, 'Tools & technologies taught in this course', ''],
      [90, 'Syllabus / topics (module-wise or week-wise breakdown)', ''],
      [91, '2-3 real projects students will build during the course', ''],
      [92, 'Course instructor name', ''],
      [93, 'Certificate title students receive on completion', ''],
      ['', '--- REPEAT the above questions for each additional course ---', ''],
    ],
  },

  // ── SHEET 6 : TRAINERS & TEAM ─────────────────────────────────────────────
  {
    name: '6. Trainers & Team',
    rows: [
      ['#', 'Question (Fill for EACH trainer on your team)', 'Your Answer'],
      ['', '--- TRAINER PROFILES PAGE HEADER STATS ---', ''],
      [94,  'Total number of expert trainers on the team (currently: 15+)', ''],
      [95,  'Combined years of experience across all trainers (currently: 120+ years)', ''],
      [96,  'Total students mentored so far (currently: 500+)', ''],
      [97,  'Student satisfaction percentage (currently: 95%)', ''],
      ['', '--- FOR EACH TRAINER, FILL THE FOLLOWING ---', ''],
      [98,  'Full name', ''],
      [99,  'Designation / Role (e.g. Lead Trainer – Full Stack)', ''],
      [100, 'Subject / course they teach', ''],
      [101, 'Professional headshot photo (clear, min 400x400px)', 'Share Google Drive link'],
      [102, 'Years of experience', ''],
      [103, 'Companies previously worked at (list all)', ''],
      [104, 'Educational qualification (degree + college name)', ''],
      [105, 'Short bio (3-5 sentences about background and teaching style)', ''],
      [106, 'Key skills / areas of expertise (5-6 tags)', ''],
      [107, 'Notable achievements (certifications, conference talks, projects, etc.)', ''],
      [108, 'LinkedIn profile URL', ''],
      [109, 'GitHub profile URL (if applicable)', ''],
      [110, 'Professional email (trainer@scopeaihub.com)', ''],
      ['', '--- REPEAT the above questions for each additional trainer ---', ''],
    ],
  },

  // ── SHEET 7 : ADMISSIONS & FEES ───────────────────────────────────────────
  {
    name: '7. Admissions & Fees',
    rows: [
      ['#', 'Question', 'Your Answer'],
      ['', '--- ENROLLMENT PROCESS (4 steps shown on Admissions page) ---', ''],
      [111, 'Step 1 — title and description (currently: Explore & Apply)', ''],
      [112, 'Step 2 — title and description (currently: Counseling Session)', ''],
      [113, 'Step 3 — title and description (currently: Confirm Enrollment)', ''],
      [114, 'Step 4 — title and description (currently: Start Learning)', ''],
      ['', '--- ELIGIBILITY CRITERIA ---', ''],
      [115, 'Minimum educational qualification required (e.g. 10+2 / Any degree)', ''],
      [116, 'Is there a minimum age requirement?', ''],
      [117, 'Do students need prior coding/tech experience for beginner courses?', ''],
      [118, 'Are there any entrance tests or interviews before joining?', ''],
      ['', '--- BATCH SCHEDULES (3 types) ---', ''],
      [119, 'Weekday batch — days (Mon-Fri?) and timings', ''],
      [120, 'Evening batch — days and timings (for working professionals)', ''],
      [121, 'Weekend batch — days (Sat-Sun?) and timings', ''],
      [122, 'Next batch start dates (per course or general)', ''],
      ['', '--- FEE STRUCTURE ---', ''],
      [123, 'Short courses (1-2 months) — fee range (currently: Rs. 15k-25k)', ''],
      [124, 'Career programs (4-6 months) — fee range (currently: Rs. 35k-55k)', ''],
      [125, 'Masters programs (8-12 months) — fee range (currently: Rs. 65k-85k)', ''],
      ['', '--- SCHOLARSHIPS & DISCOUNTS ---', ''],
      [126, 'Early bird discount — available? How much off? Any deadline?', ''],
      [127, 'Merit scholarship — available? What are the eligibility criteria?', ''],
      [128, 'Group discount — available? Minimum group size? How much off?', ''],
      ['', '--- PAYMENT OPTIONS ---', ''],
      [129, 'EMI available? How many months? 0% interest?', ''],
      [130, 'Is there a "Pay After Placement" option? Any conditions?', ''],
      [131, 'Payment methods accepted (UPI / Cash / Net Banking / Card)', ''],
    ],
  },

  // ── SHEET 8 : STUDENT TESTIMONIALS ───────────────────────────────────────
  {
    name: '8. Student Testimonials',
    rows: [
      ['#', 'Question (Provide at least 6 real student reviews)', 'Your Answer'],
      ['', '--- REVIEWS PAGE STATS ---', ''],
      [132, 'Average student rating out of 5 (currently: 4.9)', ''],
      [133, 'Total number of verified reviews (currently: 100+)', ''],
      [134, 'Student satisfaction percentage (currently: 98%)', ''],
      ['', '--- FOR EACH STUDENT REVIEW ---', ''],
      [135, 'Student full name', ''],
      [136, 'Current job role & company (e.g. Full Stack Developer at Zoho)', ''],
      [137, 'Course they completed at Scope AI Hub', ''],
      [138, 'Their review / testimonial in their own words', ''],
      [139, 'Star rating out of 5', ''],
      [140, 'Student profile photo', 'Share Google Drive link'],
      [141, 'Approximate date of review (e.g. January 2026)', ''],
      ['', '--- REPEAT the above 7 fields for each additional student ---', ''],
    ],
  },

  // ── SHEET 9 : FAQ PAGE ────────────────────────────────────────────────────
  {
    name: '9. FAQ Page',
    rows: [
      ['#', 'FAQ Question', 'Confirm Current Answer OR Write Your Own'],
      ['', '--- GENERAL ---', ''],
      [142, 'What makes Scope AI Hub different from other institutes?',
       'We focus on project-based learning and industrial training...'],
      [143, 'Do I need any prior coding experience to join?',
       'Not necessarily. We have beginner-friendly courses...'],
      [144, 'Are your certificates recognized by companies?',
       'Yes, our certificates are well-recognized in the industry...'],
      ['', '--- ADMISSIONS & FEES ---', ''],
      [145, 'How can I enroll in a course?', ''],
      [146, 'What is the fee structure?', ''],
      [147, 'Do you offer any discounts or scholarships?', ''],
      ['', '--- PLACEMENTS ---', ''],
      [148, 'Do you guarantee a job after completion?', ''],
      [149, 'What is the average salary package for freshers?', ''],
      [150, 'Which companies hire from Scope AI Hub?', ''],
      ['', '--- COURSES & CURRICULUM ---', ''],
      [151, 'What programming languages do you teach?', ''],
      [152, 'How long are your courses?', ''],
      [153, 'Will I build real projects during the course?', ''],
      [154, 'Do you teach AI and Machine Learning?', ''],
      [155, 'Can I switch courses after enrollment?', ''],
      ['', '--- LEARNING MODES ---', ''],
      [156, 'Do you offer online classes?', ''],
      [157, 'Will I get recorded sessions after each class?', ''],
      [158, 'Can I attend classes if I am working full-time?', ''],
      ['', '--- TECHNICAL & SUPPORT ---', ''],
      [159, 'What support do I get after completing the course?', ''],
      [160, 'Do I need a laptop with specific requirements?', ''],
      [161, 'Will I get 1-on-1 mentorship?', ''],
      [162, 'What if I miss a class?', ''],
    ],
  },

  // ── SHEET 10 : JOIN AS TRAINER ────────────────────────────────────────────
  {
    name: '10. Join As Trainer',
    rows: [
      ['#', 'Question', 'Your Answer'],
      ['', '--- TRAINER RECRUITMENT ---', ''],
      [163, 'Are you currently hiring trainers? (Yes / No)', ''],
      [164, 'Which subjects or roles are you hiring for?', ''],
      [165, 'Email address where trainer applicants should send their resume', ''],
      ['', '--- TRAINER REQUIREMENTS (shown on Join as Trainer page) ---', ''],
      [166, 'Minimum industry experience required (currently: 5+ years)', ''],
      [167, 'Minimum weekly time commitment required (currently: 4-6 hours/week)', ''],
      [168, 'Language requirement (currently: English required, Tamil a plus)', ''],
      [169, 'Any other requirements you want to mention?', ''],
      ['', '--- TRAINER BENEFITS (shown on the page to attract trainers) ---', ''],
      [170, 'Benefit 1 title & description (currently: Flexibility — flexible batch timings)', ''],
      [171, 'Benefit 2 title & description (currently: Pedagogical Support — materials provided)', ''],
      [172, 'Benefit 3 title & description (currently: Global Reach — online students)', ''],
      [173, 'Benefit 4 title & description (currently: Industry Networking)', ''],
    ],
  },

  // ── SHEET 11 : LEGAL & POLICIES ──────────────────────────────────────────
  {
    name: '11. Legal & Policies',
    rows: [
      ['#', 'Question', 'Your Answer'],
      ['', '--- BUSINESS REGISTRATION ---', ''],
      [174, 'Legal / registered business name (as per government registration)', ''],
      [175, 'GST number (if registered — optional)', ''],
      [176, 'Registered business address (if different from campus)', ''],
      ['', '--- REFUND POLICY ---', ''],
      [177, 'Within how many days can a student request a full refund?', ''],
      [178, 'Under what conditions is a refund given?', ''],
      [179, 'Is there a partial refund option? If yes, explain the conditions', ''],
      ['', '--- PRIVACY & GRIEVANCE ---', ''],
      [180, 'Name of the Grievance Officer (person students contact for complaints)', ''],
      [181, 'Grievance Officer email or phone number', ''],
      [182, 'Payment gateway you use (e.g. Razorpay, Stripe, or other)', ''],
    ],
  },

  // ── SHEET 12 : MEDIA ASSETS ───────────────────────────────────────────────
  {
    name: '12. Media Assets',
    rows: [
      ['#', 'Asset Required', 'Share Google Drive / Folder Link'],
      ['', '--- VIDEO ---', ''],
      [183, 'Hero background video — campus, workspace, or students in action (MP4 format, 10-30 seconds)', ''],
      ['', '--- PHOTOS ---', ''],
      [184, 'Classroom or workspace photos — real interior shots (minimum 4-5 photos)', ''],
      [185, 'Team / founder photos for About page', ''],
      [186, 'Trainer professional headshots — one per trainer (clear, square crop preferred)', ''],
      [187, 'Student placement / success photos for testimonials', ''],
      ['', '--- LOGO & BRANDING ---', ''],
      [188, 'Logo — Light version (for dark backgrounds) — PNG with transparent bg', 'Already confirmed by client'],
      [189, 'Logo — Dark version (for light backgrounds) — PNG with transparent bg', 'Already confirmed by client'],
      [190, 'Favicon — Square icon (512x512 PNG) for browser tab', ''],
      ['', '--- CERTIFICATION / PARTNER LOGOS ---', ''],
      [191, 'NASSCOM logo file (if certified)', ''],
      [192, 'ISO certification logo file (if certified)', ''],
      [193, 'MSME logo file (if registered)', ''],
      [194, 'FutureSkills Prime logo file (if affiliated)', ''],
      [195, 'Any hiring partner company logos (for the scrolling marquee)', ''],
    ],
  },

  // ── SHEET 13 : LIVE CHAT ──────────────────────────────────────────────────
  {
    name: '13. Live Chat (Optional)',
    rows: [
      ['#', 'Question', 'Your Answer'],
      [196, 'Do you want a live chat widget on the website? (Yes / No)', ''],
      [197, 'If Yes — Which chat tool? (Tawk.to is free and recommended)', ''],
      [198, 'If using Tawk.to — Property ID', ''],
      [199, 'If using Tawk.to — Widget ID', ''],
      ['', '--- NOTE ---', ''],
      ['', 'Tawk.to is completely free. Sign up at https://www.tawk.to and share the above IDs.', ''],
    ],
  },

];

// ── BUILD WORKBOOK ─────────────────────────────────────────────────────────
const wb = XLSX.utils.book_new();

sections.forEach(({ name, rows }) => {
  const ws = makeSheet(rows);
  XLSX.utils.book_append_sheet(wb, ws, name);
});

XLSX.writeFile(wb, './ScopeAIHub_Client_Questionnaire.xlsx');
console.log('Excel file generated: ScopeAIHub_Client_Questionnaire.xlsx');
