"""initial_schema

Revision ID: 90565485b80d
Revises: 
Create Date: 2026-02-24 18:58:05.237095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90565485b80d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_phone', sa.String(length=10), nullable=False),
    sa.Column('user_location', sa.String(length=255), nullable=False),
    sa.Column('qualification', sa.String(length=50), nullable=False),
    sa.Column('course_interest', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email', 'course_interest', 'created_at', name='uq_student_email_course_ts')
    )
    op.create_index(op.f('ix_student_submissions_created_at'), 'student_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_student_submissions_is_deleted'), 'student_submissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_student_submissions_user_email'), 'student_submissions', ['user_email'], unique=False)
    op.create_table('trainer_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainer_name', sa.String(length=100), nullable=False),
    sa.Column('trainer_email', sa.String(length=255), nullable=False),
    sa.Column('trainer_phone', sa.String(length=10), nullable=False),
    sa.Column('experience', sa.String(length=2), nullable=False),
    sa.Column('expertise', sa.String(length=100), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Trainer application submissions from TrainerForm.jsx'
    )
    op.create_index(op.f('ix_trainer_submissions_created_at'), 'trainer_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_trainer_submissions_is_deleted'), 'trainer_submissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_trainer_submissions_trainer_email'), 'trainer_submissions', ['trainer_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainer_submissions_trainer_email'), table_name='trainer_submissions')
    op.drop_index(op.f('ix_trainer_submissions_is_deleted'), table_name='trainer_submissions')
    op.drop_index(op.f('ix_trainer_submissions_created_at'), table_name='trainer_submissions')
    op.drop_table('trainer_submissions')
    op.drop_index(op.f('ix_student_submissions_user_email'), table_name='student_submissions')
    op.drop_index(op.f('ix_student_submissions_is_deleted'), table_name='student_submissions')
    op.drop_index(op.f('ix_student_submissions_created_at'), table_name='student_submissions')
    op.drop_table('student_submissions')
    # ### end Alembic commands ###
